// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateKey(arg1) {
  return window['go']['processor']['CharlesGenerator']['GenerateKey'](arg1);
}
