// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressJson(arg1, arg2) {
  return window['go']['processor']['JsonProcessor']['CompressJson'](arg1, arg2);
}

export function FormatJson(arg1, arg2) {
  return window['go']['processor']['JsonProcessor']['FormatJson'](arg1, arg2);
}
