// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressJson(arg1:string,arg2:boolean):Promise<string>;

export function FormatJson(arg1:string,arg2:boolean):Promise<string>;
