// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressXML(arg1:string):Promise<string>;

export function FormatXML(arg1:string):Promise<string>;
