// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate(arg1, arg2) {
  return window['go']['app']['App']['CheckForUpdate'](arg1, arg2);
}

export function CloseWindow() {
  return window['go']['app']['App']['CloseWindow']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function IsFullscreen() {
  return window['go']['app']['App']['IsFullscreen']();
}

export function LoadWindowSettings() {
  return window['go']['app']['App']['LoadWindowSettings']();
}

export function MinimizeWindow() {
  return window['go']['app']['App']['MinimizeWindow']();
}

export function ResetWindowSize() {
  return window['go']['app']['App']['ResetWindowSize']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveWindowSettings() {
  return window['go']['app']['App']['SaveWindowSettings']();
}

export function SetVersion(arg1) {
  return window['go']['app']['App']['SetVersion'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['app']['App']['ToggleFullscreen']();
}
