// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {context} from '../models';
import {config} from '../models';
import {file} from '../models';

export function CheckForUpdate(arg1:string,arg2:string):Promise<updater.UpdateInfo>;

export function CloseWindow():Promise<void>;

export function GetContext():Promise<context.Context>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsFullscreen():Promise<boolean>;

export function LoadWindowSettings():Promise<config.WindowSettings>;

export function MinimizeWindow():Promise<void>;

export function ResetWindowSize():Promise<void>;

export function SaveFile(arg1:string,arg2:file.SaveOptions,arg3:boolean):Promise<string>;

export function SaveWindowSettings():Promise<void>;

export function SetVersion(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleFullscreen():Promise<void>;
