// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function GenerateCharlesKey(arg1) {
  return window['go']['main']['App']['GenerateCharlesKey'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsFullscreen() {
  return window['go']['main']['App']['IsFullscreen']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
