// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressXML(arg1) {
  return window['go']['main']['XMLProcessor']['CompressXML'](arg1);
}

export function FormatXML(arg1) {
  return window['go']['main']['XMLProcessor']['FormatXML'](arg1);
}
